// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.BetaBot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3824.BetaBot.Robot;
import org.usfirst.frc3824.BetaBot.Constants;

/**
 *
 */
public class BoulderIntakeControl extends Command
{
	private boolean m_manual_enabled;
	
	private double desired_position;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private double m_IntakePosition;
	private boolean m_roll;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public BoulderIntakeControl(double IntakePosition, boolean roll)
	{

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		m_IntakePosition = IntakePosition;
		m_roll = roll;

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.boulderIntake);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		// Assume not in manual mode
		m_manual_enabled = false;
	
		// Low power for normal mode
		Robot.boulderIntake.setBoulderControlPowerRange(Constants.BOULDER_INTAKE_RETRACT_POWER, Constants.BOULDER_INTAKE_EXTEND_POWER);
		
		// Remember the desired intake position
		desired_position = m_IntakePosition;
		
		if (m_IntakePosition == Constants.BOULDER_INTAKE_HOME_BUTTON)
		{
			// Rest Position
			desired_position = 0.0;
		}
		else if (m_IntakePosition == Constants.BOULDER_INTAKE_MAX_EXTEND_BUTTON)
		{
			// Maximum down
			desired_position = 1.0;
		}
		else if (m_IntakePosition == Constants.BOULDER_INTAKE_BOULDER_BUTTON)
		{
			// Intake Position
			desired_position = 0.95;
		}
		else if (m_IntakePosition == Constants.BOULDER_INTAKE_MANUFAL_BUTTON)
		{
			m_manual_enabled = true;
			
			// Allow full power for Port Cullus
			// Note: Just need to increase up power
			Robot.boulderIntake.setBoulderControlPowerRange(-1.0, Constants.BOULDER_INTAKE_EXTEND_POWER);
			
			// Get the potentiometer position from the control panel
			// Note: X position -1 to 1 and desired position is from 0 to 1
			desired_position = (Robot.oi.controllerJoystick.getX() + 1.0) / 2.0;
		}
		
		SmartDashboard.putNumber("Boulder Position", desired_position);

		// Set the boulder intake desired potentiometer position
		Robot.boulderIntake.SetPID_Position(desired_position);

		// enable the boulder intake PIDs
		Robot.boulderIntake.EnableBoulderIntakePID();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		// Determine if manual mode is enabled
		if (m_manual_enabled)
		{
			// Get the potentiometer position from the control panel
			// Note: X position -1 to 1 and desired position is from 0 to 1
			desired_position = (Robot.oi.controllerJoystick.getX() + 1.0) / 2.0;
			
			// Set the boulder intake desired potentiometer position
			Robot.boulderIntake.SetPID_Position(desired_position);
		}
		
		if (m_roll == true)
		{
			Robot.boulderIntake.setBoulderIntakeWheelSpeed(Constants.BOULDER_ROLLER_SPEED);
		}
		else
		{
			Robot.boulderIntake.setBoulderIntakeWheelSpeed(0);
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		return false;
	}

	// Called once after isFinished returns true
	protected void end()
	{
		Robot.boulderIntake.setBoulderIntakeWheelSpeed(0);
		
		// disable the PID
		Robot.boulderIntake.DisableBoulderIntakePID();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		this.end();
	}
}
